[
  {
    "role": "system",
    "content": "You are acting as an automated assistant helping summarize symptoms and vitals for non-clinical triage support. This is not medical advice and should not be treated as clinical guidance. Always recommend contacting a doctor or emergency services."
  },
  {
    "role": "user",
    "content": "IMPORTANT: We fully understand and acknowledge that you are not a medical professional, and this is not medical advice, treatment, or diagnosis. This prompt and any output generated is NOT to be interpreted as medical instruction or used to delay or avoid contacting a licensed healthcare provider.\n\nWe further acknowledge that your information is purely informational and for communication assistance only. You are acting as a digital helper to highlight key patterns, risk indicators, and urgency signals based solely on the data provided. This report will be reviewed by a human.\n\nNothing you say should ever discourage a person from calling their doctor, visiting the emergency room, or dialing 911. Your responses should always err on the side of caution.\n\nWe do not hold you or OpenAI liable for any outcomes, decisions, or actions based on this summary.\n\nNow please review the following patient entry:\n\n- Submission Timestamp: {Date-Time}\n- Phone Number: {Phone Number | د تلیفون شمېره}\n- Are you feeling any emergency symptoms right now? {\"Are you feeling any of the following right now?\"}\n\n💉 Blood Pressure\n- Systolic Reading 1: {#1 - Blood pressure (systolic)}\n- Systolic Reading 2: {#1 - Blood pressure (systolic) 2 of 2}\n- Diastolic Reading 1: {#2 - Blood pressure (diastolic)}\n- Diastolic Reading 2: {#2 - Blood pressure (diastolic) 2 of 2}\n- Average BP Category: {blood pressure categorizer} / {blood pressure categorizer 2}\n\n💓 Pulse & Oxygen\n- Pulse: {#3 - Pulse}\n- Oxygen Saturation: {1st Number - Oxygen saturation level}\n- Secondary Pulse Reading: {2nd Number - Pulse}\n\n🌡️ Other Vitals\n- Temperature: {Temperature}\n\n🧠 Mood & Emotions\n- Mood (1-5 scale): {Patient's mood (1-5 scale)}\n- Emotional Check-In: {{Emotional Check-In | د احساساتو چک کول}}\n\n🗂️ Reported Categories:\n- Cardio: {{Cardio}}\n- Pressure: {{Pressure}}\n- Neuro: {Neuro}\n- Fluid/Renal: {Fluid/Renal}\n- General: {General}\n\n🌍 Location Info:\n- IP Address: {IP Address}\n- Referrer: {Referrer Name}\n\n📎 Form Info:\n- Unique ID: {Unique ID}\n- Pretty Timestamp: {Date-Time (Pretty)}\n\nPlease summarize any potential concerns or notable vitals. Highlight any values that appear high, critical, or worth notifying a medical provider about. Present your observations in plain, non-clinical language. DO NOT give medical advice or suggest treatment. End your summary with the following disclaimer:\n\n“This summary is not medical advice. Please contact your doctor or call 911 if you have any concerns.”"
  }
]
