version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  qilife-app:
    build: .
    container_name: qilife-app
    restart: on-failure
    ports:
      - "8501:8501"              # Streamlit UI
    environment:
      QDRANT_URL: "http://qdrant:6333"
      # if using OpenAI embeddings:
      # OPENAI_API_KEY: "${OPENAI_API_KEY}"
    depends_on:
      - qdrant
