import pandas as pd

# Define the account data
account_data = [
    # Business Assets
    {"Full name": "Business Assets", "Parent account name": "", "Account Number": "B100", "Type": "Other Current Assets",
     "Detail type": "Other Current Assets", "Description": "Business", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Business Uncategorized Asset", "Parent account name": "Business Assets", "Account Number": "B190",
     "Type": "Other Current Assets", "Detail type": "Other Current Assets", "Description": "Uncategorized Asset",
     "Account": "", "Parent account id": "", "Is sub:account (Y/N)": "No"},

    # Business Liabilities
    {"Full name": "Business Liabilities", "Parent account name": "", "Account Number": "B200", "Type": "Other Current Liabilities",
     "Detail type": "Other Current Liabilities", "Description": "Business", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Business Deferred Revenue", "Parent account name": "Business Liabilities", "Account Number": "B210",
     "Type": "Other Current Liabilities", "Detail type": "Deferred Revenue", "Description": "Deferred Revenue",
     "Account": "", "Parent account id": "", "Is sub:account (Y/N)": "No"},
    {"Full name": "Business Liability 1", "Parent account name": "Business Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Business Liability 1",
     "Account": "", "Parent account id": "B200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Business Liability 2", "Parent account name": "Business Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Business Liability 2",
     "Account": "", "Parent account id": "B200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Business Liability 3", "Parent account name": "Business Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Description": "Business Liability 3",
     "Account": "", "Parent account id": "B200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Business Liability 4", "Parent account name": "Business Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Description": "Business Liability 4",
     "Account": "", "Parent account id": "B200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Business Liability 5", "Parent account name": "Business Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Business Liability 5",
     "Account": "", "Parent account id": "B200", "Is sub:account (Y/N)": "Yes"},

    # Schedule C Income
    {"Full name": "SchC:Income", "Parent account name": "", "Account Number": "B400", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "SchC:Income:Tax", "Parent account name": "SchC:Income", "Account Number": "B410", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "B400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Income:Accounting", "Parent account name": "SchC:Income", "Account Number": "B420", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "B400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Income:General", "Parent account name": "SchC:Income", "Account Number": "B430", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "B400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Income:IT", "Parent account name": "SchC:Income", "Account Number": "B440", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "B400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Income:Other", "Parent account name": "SchC:Income", "Account Number": "B480", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "B400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Shipping Income", "Parent account name": "", "Account Number": "B481", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "Shipping Income", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Billable Expense Income", "Parent account name": "", "Account Number": "B482", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Markup", "Parent account name": "", "Account Number": "B483", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "Markup", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Services", "Parent account name": "", "Account Number": "B484", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "Services", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Uncategorized Income", "Parent account name": "", "Account Number": "B485", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "Uncategorized Income", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Late Fee Income", "Parent account name": "", "Account Number": "B486", "Type": "Other Income",
     "Detail type": "Other Miscellaneous Income", "Description": "Late Fee Income", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Tips Income", "Parent account name": "", "Account Number": "B487", "Type": "Other Income",
     "Detail type": "Other Investment Income", "Description": "Tips Income", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Discounts given", "Parent account name": "", "Account Number": "B495", "Type": "Income",
     "Detail type": "Discounts/Refunds Given", "Description": "Discounts given", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},

    # Schedule C Expenses
    {"Full name": "SchC", "Parent account name": "", "Account Number": "B500", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "", "Is sub:account (Y/N)": "No"},
    {"Full name": "SchC:Advertising", "Parent account name": "SchC", "Account Number": "B501", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto", "Parent account name": "SchC", "Account Number": "B510", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto:Fuel", "Parent account name": "SchC:Auto", "Account Number": "B511", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto:Insurance", "Parent account name": "SchC:Auto", "Account Number": "B512", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto:LeasePayments", "Parent account name": "SchC:Auto", "Account Number": "B513", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto:Maintenance", "Parent account name": "SchC:Auto", "Account Number": "B514", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto:MileageAdjustment", "Parent account name": "SchC:Auto", "Account Number": "B515",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto:Registration", "Parent account name": "SchC:Auto", "Account Number": "B516", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Auto:Repairs", "Parent account name": "SchC:Auto", "Account Number": "B517", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Commissions", "Parent account name": "SchC", "Account Number": "B520", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:ContractLabor", "Parent account name": "SchC", "Account Number": "B521", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Depreciation", "Parent account name": "SchC", "Account Number": "B522", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:EmployeeBenefits", "Parent account name": "SchC", "Account Number": "B523", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Insurance", "Parent account name": "SchC", "Account Number": "B524", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:LegalProfessional", "Parent account name": "SchC", "Account Number": "B525", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Meals", "Parent account name": "SchC", "Account Number": "B526", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:MortgageInterest", "Parent account name": "SchC", "Account Number": "B527", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OfficeExpense", "Parent account name": "SchC", "Account Number": "B530", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses", "Parent account name": "SchC", "Account Number": "B540", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses:BankFees", "Parent account name": "SchC:OtherExpenses", "Account Number": "B541",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses:BusinessGifts", "Parent account name": "SchC:OtherExpenses", "Account Number": "B542",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses:DuesMemberships", "Parent account name": "SchC:OtherExpenses", "Account Number": "B543",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses:Education", "Parent account name": "SchC:OtherExpenses", "Account Number": "B544",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses:Postage", "Parent account name": "SchC:OtherExpenses", "Account Number": "B545",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses:Software", "Parent account name": "SchC:OtherExpenses", "Account Number": "B546",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:OtherExpenses:Subscriptions", "Parent account name": "SchC:OtherExpenses", "Account Number": "B547",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
     {"Full name": "SchC:OtherInterest", "Parent account name": "SchC:OtherExpenses", "Account Number": "B548",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:PensionPlans", "Parent account name": "SchC", "Account Number": "B550", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:RentOther", "Parent account name": "SchC", "Account Number": "B551", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:RentVehicles", "Parent account name": "SchC", "Account Number": "B552", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:RepairsMaintenance", "Parent account name": "SchC", "Account Number": "B553", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Supplies", "Parent account name": "SchC", "Account Number": "B554", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:TaxesLicenses", "Parent account name": "SchC", "Account Number": "B555", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Travel", "Parent account name": "SchC", "Account Number": "B560", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Travel: Lodging", "Parent account name": "SchC:Travel", "Account Number": "B561", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B560",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Travel:Meals", "Parent account name": "SchC:Travel", "Account Number": "B562", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B560",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Travel:Parking Tolls", "Parent account name": "SchC:Travel", "Account Number": "B563",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B560",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Utilities", "Parent account name": "SchC", "Account Number": "B570", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "SchC:Wages", "Parent account name": "SchC", "Account Number": "B571", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Uncategorized Expense", "Parent account name": "SchC", "Account Number": "B590", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "Uncategorized Expense", "Account": "", "Parent account id": "B500",
     "Is sub:account (Y/N)": "Yes"},

    # Personal Assets
    {"Full name": "Pers:Assets", "Parent account name": "", "Account Number": "P100", "Type": "Other Current Assets",
     "Detail type": "Other Current Assets", "Description": "Pers Assets", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Home", "Parent account name": "Pers:Assets", "Account Number": "", "Type": "Other Current Assets",
     "Detail type": "Other Current Assets", "Description": "Home", "Account": "", "Parent account id": "P100",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Uncategorized Asset", "Parent account name": "Pers:Assets", "Account Number": "P190",
     "Type": "Other Current Assets", "Detail type": "Other Current Assets", "Description": "", "Account": "",
     "Parent account id": "P100", "Is sub:account (Y/N)": "No"},

    # Personal Liabilities
    {"Full name": "Pers:Liabilities", "Parent account name": "", "Account Number": "P200",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Person", "Account": "",
     "Parent account id": "", "Is sub:account (Y/N)": "No"},
    {"Full name": "Home Mortgage 1", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Home Mortgage 1", "Account": "",
     "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Home Mortgage 2", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Home Mortgage 2", "Account": "",
     "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 1", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 1",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 2", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 2",
     "Account": "", "Parent account id": "P200", "Is sub:account(Y/N)": "Yes"},
    {"Full name": "Personal Liability 3", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 3",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 4", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 4",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 5", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 5",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 6", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 6",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 7", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 7",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 8", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 8",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 9", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 9",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 10", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 10",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 11", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 11",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 12", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 12",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 13", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 13",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 14", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 14",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 15", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 15",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 16", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 16",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 17", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 17",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 18", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 18",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 19", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 19",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Personal Liability 20", "Parent account name": "Pers:Liabilities", "Account Number": "",
     "Type": "Other Current Liabilities", "Detail type": "Other Current Liabilities", "Description": "Personal Liability 20",
     "Account": "", "Parent account id": "P200", "Is sub:account (Y/N)": "Yes"},

    # Personal Income
    {"Full name": "Pers:Income", "Parent account name": "", "Account Number": "P400", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
    {"Full name": "Pers:Income:Wages", "Parent account name": "Pers:Income", "Account Number": "P410", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "P400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Income:Interest", "Parent account name": "Pers:Income", "Account Number": "P420", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "P400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Income:Dividends", "Parent account name": "Pers:Income", "Account Number": "P430", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "P400",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Income:Other", "Parent account name": "Pers:Income", "Account Number": "P480", "Type": "Income",
     "Detail type": "Service/Fee Income", "Description": "", "Account": "", "Parent account id": "P400",
     "Is sub:account (Y/N)": "Yes"},# Personal Expenses
    {"Full name": "Pers", "Parent account name": "", "Account Number": "P500", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "", "Is sub:account (Y/N)": "No"},
    {"Full name": "Pers:Entertainment", "Parent account name": "Pers", "Account Number": "P510", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:EntertainmentOutings", "Parent account name": "Pers:Entertainment", "Account Number": "P510",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P510",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Food", "Parent account name": "Pers", "Account Number": "P520", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:FoodDiningOut", "Parent account name": "Pers:Food", "Account Number": "P521", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P520",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:FoodGroceries", "Parent account name": "Pers:Food", "Account Number": "P522", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P520",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Gifts", "Parent account name": "Pers", "Account Number": "P525", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Health", "Parent account name": "Pers", "Account Number": "P530", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HealthInsurance", "Parent account name": "Pers:Health", "Account Number": "P531", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P530",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HealthMedical", "Parent account name": "Pers:Health", "Account Number": "P532", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P530",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Home", "Parent account name": "Pers", "Account Number": "P540", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeHOA", "Parent account name": "Pers:Home", "Account Number": "P541", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeInsurance", "Parent account name": "Pers:Home", "Account Number": "P542", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeMortgage", "Parent account name": "Pers:Home", "Account Number": "P543", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeOther", "Parent account name": "Pers:Home", "Account Number": "P544", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeRepairs", "Parent account name": "Pers:Home", "Account Number": "P545", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeTaxes", "Parent account name": "Pers:Home", "Account Number": "P546", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeUtilties", "Parent account name": "Pers:Home", "Account Number": "P547", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P540",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeUtiltiesElectric", "Parent account name": "Pers:HomeUtilties", "Account Number": "P548",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P547",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:HomeUtiltiesWater", "Parent account name": "Pers:HomeUtilties", "Account Number": "P549",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P547",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Self Care", "Parent account name": "Pers", "Account Number": "P550", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Subscriptions", "Parent account name": "Pers", "Account Number": "P555", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Transportation", "Parent account name": "Pers", "Account Number": "P560", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:Utilities", "Parent account name": "Pers", "Account Number": "P570", "Type": "Expenses",
     "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P500",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:UtilitiesInternet", "Parent account name": "Pers:Utilities", "Account Number": "P571",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P570",
     "Is sub:account (Y/N)": "Yes"},
    {"Full name": "Pers:UtilitiesTelephone", "Parent account name": "Pers:Utilities", "Account Number": "P572",
     "Type": "Expenses", "Detail type": "Other Expenses", "Description": "", "Account": "", "Parent account id": "P570",
     "Is sub:account (Y/N)": "Yes"},

    # Retained Earnings
    {"Full name": "Retained Earnings", "Parent account name": "", "Account Number": "P110", "Type": "Equity",
     "Detail type": "Retained Earnings", "Description": "", "Account": "", "Parent account id": "",
     "Is sub:account (Y/N)": "No"},
]

# Create DataFrame
df = pd.DataFrame(account_data)

# Save as Excel
excel_path = "Chart_of_Accounts_ScheduleC_and_Personal.xlsx"
try:
    df.to_excel(excel_path, index=False)
    print(f"Excel file successfully created at {excel_path}")
except PermissionError as e:
    print(f"Error: Permission denied.  Make sure the file '{excel_path}' is not already open and that you have write permissions in the directory.  Error details: {e}")

