flowchart LR
    A[qilife-main/]
    A --> app[app.py]
    A --> req[requirements.txt]
    A --> readme[README.md]
    A --> env[.env]
    A --> setup[setup_venv.ps1]
    A --> dc[docker-compose.yml]
    A --> df[dockerfile]
    A --> arch[.ARCHIVE/]
    A --> tests[tests/]
    A --> src[src/]
    
    B[src/]
    B --> core["core/"]        
    B --> monitor["monitor/"]
    B --> context["context/"]
    B --> fileflow["fileflow/"]
    B --> calls["calls/"]
    B --> messaging["messaging/"]
    B --> memory["memory/"]
    B --> gui["gui/"]
    B --> lifelog["lifelog/"]
    B --> qinote["qinote/"]
    B --> tools["tools/"]
    B --> empower["empower713/"]
    
    C[core/]
    C --> config_l[config_loader.py]
    C --> router[module_router.py]
    C --> envm[env_manager.py]
    C --> log[log_setup.py]
    
    D[monitor/]
    D --> ss[screenshot_watcher.py]
    D --> fem[file_event_monitor.py]
    D --> dst[device_state_tracker.py]
     
    E[context/]
   E --> ocr[ocr_extractor.py]
   E --> clf[text_classifier.py]
   E --> ren[file_renamer.py]
   E --> meta[metadata_extractor.py]
   E --> sumr[summarizer.py]

   F[fileflow/]
   E --> mover[mover.py]
   E --> fm[folder_merger.py]
   E --> rr[rename_rules.py]
   E --> fc[folder_creator.py]
   E --> cons[consolidator.py]

   CALLS[calls/]
   E --> handler[call_handler.py]
   E --> trans[voice_transcriber.py]
   E --> elabs[elevenlabs_interface.py]
   E --> vm[voicemail_router.py]

   MSG[messaging/]
   E --> sms[sms_router.py]
   E --> email[email_parser.py]
   E --> webhook[webhook_handler.py]
   E --> sync[conversation_sync.py]

   MEMORY["memory/"]
   E --> emb[embedder.py]
   E --> vect[vector_store.py]
   E --> ret[retriever.py]
   E --> mlog[memory_logger.py]

   GUI["gui/"]
   E --> mw[main_window.py]
   E --> splash[splash_screen.py]
   E --> components[components/]
   E --> styles[styles/]

   COMPONENTS["components/"]
   E --> timeline[timeline.py]
   E --> filereview[file_review.py]
   E --> folderpick[folder_picker.py]
   E --> logexport[log_export.py]

   LIFELOG["lifelog/"]
   E --> ing[ingestion.py]
   E --> digest[digest_creator.py]
   E --> spyme[spyme.py]
   E --> notion[notion_logger.py]
   E --> actfeed[activity_feeder.py]

   QINOTE["qinote/"]
   E --> node[node_manager.py]
   E --> tmpl[template_engine.py]
   E --> refl[reflection_api.py]
   E --> nclean[notion_cleanup.py]

   TOOLS["tools/"]
   E --> ai[ai/]
   E --> fileops[fileops/]
   E --> folderops[folderops/]
   E --> config[config/]
  E -->  logs[logs/]
  E -->  idx[index/]
   E --> utils[utils/]

   AI["ai/"]
  E -->  pr[prompt_runner.py]
  E -->  ssum[summarizer.py]
  E -->  clf2[classifier.py]

   FILEOPS["fileops/"]
   E --> pdf[pdf_tools.py]
   E --> img2txt[image_to_text.py]
   E --> html[html_parser.py]

   EMPOWER["empower713/"]
  E -->  manf[manifesto.md]
   E --> brand[brand_intro.txt]
  E -->  corep[core_principles.py]



